language: python

matrix:
  include:
    - name: "Python 3.5"
      python: "3.5"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.7"
      python: "3.7"
      dist: xenial

install:
  - pip install -r requirements.txt

script:
  - travis_wait env NOSE_IGNORE_CONFIG_FILES=y make check coverage docs COVERAGE=coverage SPHINXAPIDOC=sphinx-apidoc

notifications:
  email:
    on_success: change
    on_failure: change
