language: python
dist: xenial
sudo: true

matrix:
  include:
    - name: "Python 3.5"
      python: "3.5"
      branches:
        only:
        - master
        - rhel8-branch
    - name: "Python 3.6"
      python: "3.6"
      branches:
        only:
        - master
        - rhel8-branch
    - name: "Python 3.7"
      python: "3.7"
      branches:
        only:
        - master
        - rhel8-branch

install:
  - pip install -r requirements.txt

script:
  - travis_wait env NOSE_IGNORE_CONFIG_FILES=y make check coverage docs COVERAGE=coverage

notifications:
  email:
    on_success: change
    on_failure: change
