language: python
python:
  - "3.5"

install:
  - pip install --upgrade pip setuptools
  - pip install coverage nose ordered-set polib pylint requests six Sphinx
  - pip install https://github.com/rhinstaller/pocketlint/zipball/master

script:
  - travis_wait make check coverage docs

notifications:
  email:
    on_success: change
    on_failure: change
