language: python
dist: xenial

jobs:
  include:
    - name: "Python 3.5"
      python: "3.5"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.8"
      python: "3.8"
    - name: "Python Nightly"
      python: "nightly"
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt

script:
  - travis_wait make check coverage docs COVERAGE=coverage SPHINXAPIDOC=sphinx-apidoc

after_success:
  - |

      coverage combine
      coveralls

notifications:
  email:
    on_success: change
    on_failure: change
